### ISSUE TITLE
Missing ContainSagaData class

### ISSUE THREAD

**Issue by willwolfram18** [Particular/NServiceBus.Storage.MongoDB#15]
In reading the "[Saga data class changes](https://docs.particular.net/persistence/mongodb/migrating-from-sbmako#saga-data-class-changes)" for migrating from NServiceBus.MongoDB, there is link that takes you to a code snippet showing a `ContainSagaData` class that can be used instead of implementing the `IContainSagaData` interface directly. However, it appears this `ContainSagaData` class is missing from the current alpha build. While it's not a critical issue since users can implement the interface directly, it would be nice to have feature parity with other storage mechanisms.

**Comment by boblangley** [comment]
The `ContainSagaData` abstract class is provided by the NServiceBus core library https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Sagas/ContainSagaData.cs

This file exists in the `NServiceBus` namespace.

**Comment by willwolfram18** [comment]
Ah there we go! For some reason my tooling wasn't detecting the class and told me such a class didn't exist. Then I did some digging into the Sql persistence library and found the `ContainSagaData` class. Apparently I misread the search results though, because that library is only inheriting from it (I thought I saw it defined there).

Sorry about that! Thanks for pointing it out! 😄

**Comment by timbussmann** [comment]
Glad to hear that you were able to sort it out 👍 SQLP indeed has some custom saga related classes as it handles things slightly differently for the SQL script generation but that won't be necessary for MongoDB.
