### ISSUE TITLE
Transactions are now supported by some configurations other than replica set

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.Storage.MongoDB#28]
This line checks that the configuration of the server is a Replica Set:

https://github.com/Particular/NServiceBus.Storage.MongoDB/blob/master/src/NServiceBus.Storage.MongoDB/SynchronizedStorage/SynchronizedStorage.cs#L36

This was true during implementation but has since changed: https://docs.mongodb.com/manual/core/transactions/#feature-compatibility-version-fcv

This check should be updated or removed.

## Who's affected

Users on MongoDB 4.2 or above using a sharded cluster are unable to use the persistence because of the check

## Symptoms

An exception will be thrown stating:
> Transactions are only supported on a replica set. Disable support for transactions by calling 'EndpointConfiguration.UsePersistence<MongoPersistence>().UseTransactions(false)'

**Comment by timbussmann** [comment]
Starting with version 2.1, NServiceBus.Storage.MongoDB is also able to connect to sharded clusters.
