### ISSUE TITLE
Support resolving the MongoDB client from DI

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Storage.MongoDB#328]
We should allow a [client provider to be registered in DI similar to Azure table persistence](https://docs.particular.net/persistence/azure-table/configuration#configuring-a-cloud-table-client-provider)

**Comment by timbussmann** [comment]
This has been implemented in version 2.3.0 of the MongoDB persister via https://github.com/Particular/NServiceBus.Storage.MongoDB/pull/353. With this version an `IMongoSynchronizedStorageSession` can be resolved from DI and it's `MongoSession` property provides direct access to the `IClientSessionHandle` similar to the `MongoPersistenceSession()` extension available in message handlers.
