### ISSUE TITLE
How do timeouts behave with the rabbitmq transport?

### ISSUE THREAD

**Issue by TraGicCode** [Particular/NServiceBus.Storage.MongoDB#45]
Is this similar to the RavenDB Persistance in which timeouts will automatically go to the delay queues in rabbitmq when the rabbitmq transport is being used without any special configuration?

**Comment by ramonsmits** [comment]
MongoDB persister does not support timeout storage. Timeouts are native to RabbitMQ so do not require a persister that supports timeout storage.
