### ISSUE TITLE
Mongo Driver 2.19 has a breaking change

### ISSUE THREAD

**Issue by charlessolar** [Particular/NServiceBus.Storage.MongoDB#481]
### Describe the bug

After updating my packages I found mongodb persistence is failing - error in my app is 
```
MongoDB.Bson.BsonSerializationException: Type Aggregates.Sagas.CommandSagaHandler+SagaData is not configured as an allowed type for this instance of ObjectSerializer.
at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.SerializeDiscriminatedValue(BsonSerializationContext context, BsonSerializationArgs args, Object value, Type actualType)
at MongoDB.Bson.Serialization.Serializers.DiscriminatedInterfaceSerializer`1.Serialize(BsonSerializationContext context, BsonSerializationArgs args, TInterface value)
```

Also if you notice the dependabot created a PR to upgrade the driver version and theres a lot of failed tests
https://github.com/Particular/NServiceBus.Storage.MongoDB/pull/458

The breaking change is described here:
https://github.com/mongodb/mongo-csharp-driver/releases/tag/v2.19.0

Guess it would be best to update the nuget package to enfore MongoDB.Driver <= 2.18 for the time being

### Steps to reproduce

Upgrade to MongoDB.Driver 2.19

**Comment by charlessolar** [comment]
Oh also, VS supplies a nice little warning when downgrading 
<img width="252" alt="image" src="https://user-images.githubusercontent.com/1750226/227420534-78c444cb-d3e3-4a73-9306-d9e93ef66ce7.png">

**Comment by danielmarbach** [comment]
Ok I'm confused. Why do I need to register the types again when I already have the possibility to declare a BsonClassMap? 

I guess locking it into 2.18 is also not great given the vulnerability

**Comment by danielmarbach** [comment]
I have raised a question to the forum https://www.mongodb.com/community/forums/t/object-serializer-breaking-changes-in-2-19-net-client/219020

**Comment by danielmarbach** [comment]
Apparently someone else also raised the same question https://www.mongodb.com/community/forums/t/feature-request-c-driver-to-auto-register-all-explicitly-mapped-types-as-allowed/218839

**Comment by danielmarbach** [comment]
@charlessolar I think I found a reasonable fix. See https://github.com/Particular/NServiceBus.Storage.MongoDB/pull/482

**Comment by charlessolar** [comment]
LGTM! Though I think it may be a good idea to expose the `ObjectSerializer.DefaultAllowedTypes` as part of `NServiceBus.PersistenceExtensions` too perhaps?

Just in case theres a really weird case where mongo's serializer needs to be fed a custom allowed type.

**Comment by danielmarbach** [comment]
I looked into this and I think once we have first class support for the mapping API also for the saga GET I don't think we need to expose what you proposed.

**Comment by danielmarbach** [comment]
@charlessolar I'm in the process of releasing patches for the supported versions

**Comment by danielmarbach** [comment]
@charlessolar we have released new version https://discuss.particular.net/t/nservicebus-storage-mongodb-3-0-1-and-2-3-2-patch-releases-available/3516/1
