### ISSUE TITLE
Updating MongoDB.Driver to 2.28.0 version breaks the MongoClient for v3 also

### ISSUE THREAD

**Issue by strickie** [Particular/NServiceBus.Storage.MongoDB#687]
#### Is your improvement related to a problem? Please describe.
Issue https://github.com/Particular/NServiceBus.Storage.MongoDB/issues/660 is also relavante to the v3 version of this nuget.

Would it be possible to back port it the the v3 series?

**Comment by WilliamBZA** [comment]
I've submitted a PR: https://github.com/Particular/NServiceBus.Storage.MongoDB/pull/690

**Comment by WilliamBZA** [comment]
Will be released in 3.0.4

**Comment by WilliamBZA** [comment]
3.0.4 has been release

**Comment by strickie** [comment]
> 3.0.4 has been release
@WilliamBZA 
Great. Thank you for very fast reaction.
It looks like it works for us.
💪
